#!usr/bin/env ruby

require 'net/http'
require 'json'
require 'uri'

URL = 'http://localhost:4000/'.freeze

class Request
  def self.add(val)
    uri = URI.parse(URL + 'checksum/digits')
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
    req.body = { value: val.to_i }.to_json
    http.request(req)
  end

  def self.clear
    uri = URI.parse(URL + 'checksum/digits')
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Delete.new(uri.path, 'Content-Type' => 'application/json')
    http.request(req)
  end

  def self.count_checksum
    uri = URI.parse(URL + 'checksum')
    http = Net::HTTP.new(uri.host, uri.port)
    req = Net::HTTP::Get.new(uri.path, 'Content-Type' => 'application/json')
    resp = http.request(req)
    resp.body
  end
end

# MAIN SCRIPT

raise 'Wrong number of arguments' if ARGV.length > 1
file_name = ARGV[0] || 'test_input'
output = String.new

File.readlines(file_name).each do |line|
  cmd, val = line.strip.scan(/\d+|\D+/)

  case cmd
  when 'A'
    Request.add(val)
  when 'C'
    Request.clear
  when 'CS'
    cs = Request.count_checksum
    output += cs
  when nil
    next
  end
end

puts output

